### ISSUE TITLE
Cannot add more than 50 classroom members

### ISSUE THREAD

**Issue by leoerlandsson** [lithnet/googleapps-client#2]
It's not possible to add more than 50 classroom members. 

Cause is that the TokenBucket size of *ClassroomRequestFactory* is 50, but the BatchSize of *CourseStudentRequestFactory* and *CourseTeacherRequestFactory* is 100.

Exception:
ArgumentOutOfRangeException: Number of tokens required is greated than the capacity of the bucket

Solution:
Lower the BatchSize of CourseStudentRequestFactory and CourseTeacherRequestFactory to 50.

We'll also need to change the rate limit for the ClassroomService from 5 requests per 1 second to 50 requests per 10 seconds (to harmonize with batch size).

**Comment by ryannewington** [comment]
@leoerlandsson can we close this issue off?

**Comment by leoerlandsson** [comment]
Yes, it should be working fine with this commit. 

Welcome back!

**Comment by ryannewington** [comment]
Awesome! and thanks for keeping an eye on things while I was away. Much appreciated! And feel free to keep helping out if you have the time. Contributions are always welcome and to be honest I need all the help I can get!
